config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  resources :franchises
  resources :teams
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batting_record.rb
class BattingRecord < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/fielding_record.rb
class FieldingRecord < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/franchise.rb
class Franchise < ApplicationRecord
  has_many :teams
end

app/models/pitching_record.rb
class PitchingRecord < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :batting_records
  has_many :pitching_records
  has_many :fielding_records
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :franchise
  has_many :batting_records
  has_many :pitching_records
  has_many :fielding_records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/franchises_controller.rb
class FranchisesController < ApplicationController

  def index
    @franchises = Franchise.all
  end

  def show
    @franchise = Franchise.find(params[:id])
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/franchises_helper.rb
module FranchisesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/franchises/index.html.erb
<h1>Sultan of Stat</h1>
<p>Franchises</p>

<h4>Active Franchises</h4>
  <% @franchises.where(active: true).each do |fran| %>

    <div class="team"><%= link_to fran.franchise_name, franchise_path(fran) , class: "team-link" %></div>
  <% end %>

<style>
  .team {
    width: 33%;
    text-align: center;
    display: inline-block
  }
  .team-link {
    color: #a4a4ff;
    text-decoration: none;
  }
  .team-link:hover {
    color: #ffa4a4;
    text-decoration: none;
  }
</style>

app/views/franchises/show.html.erb
<h1>Sultan of Stat</h1>
<p><%= @franchise.franchise_name %></p>

<h4>Teams Under Franchise</h4>
<ul>
  <% @franchise.teams.each do |team| %>
    <% if team.batting_records.any? %>
      <li><%= link_to "#{team.year} #{team.name}", team_path(team) %></li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SultanOfStat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/show.html.erb
<h1>Sultan of Stat</h1>
<p><%= "#{@player.first_name} #{@player.last_name}" %></p>